# Generated by Django 3.2.5 on 2021-11-09 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(default=django.utils.timezone.now, verbose_name='Create')),
                ('modified', models.DateField(default=django.utils.timezone.now, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('github_url', models.URLField(verbose_name='Github')),
                ('url', models.URLField(verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
