# Generated by Django 3.2.5 on 2021-11-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
