# Generated by Django 3.2.5 on 2021-11-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Description'),
        ),
    ]
