# Generated by Django 3.2.5 on 2021-11-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20211109_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, verbose_name='Page'),
        ),
    ]
