# Generated by Django 3.2.5 on 2021-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='responsabilities',
            field=models.TextField(blank=True, verbose_name='Responsabilities'),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.TextField(blank=True, verbose_name='Tools'),
        ),
    ]
